#
# src/cmake/LocalLibrary.cmake
#
# written by SvOlli
# distributed as public domain
#

FUNCTION( PROPAGATE_LIBRARY _NAME )

   CMAKE_PARSE_ARGUMENTS( PROPAGATE_LIBRARY "" "LIBNAME" "" ${ARGN} )

   IF( DEFINED PROPAGATE_LIBRARY_LIBNAME )
      SET( LIBNAME ${PROPAGATE_LIBRARY_LIBNAME} )
   ELSE( DEFINED PROPAGATE_LIBRARY_LIBNAME )
      SET( LIBNAME ${_NAME} )
   ENDIF( DEFINED PROPAGATE_LIBRARY_LIBNAME )

   STRING( TOUPPER ${_NAME} _NAME_UPPER )
   STRING( TOLOWER ${_NAME} _NAME_LOWER )
   
   SET( ${_NAME_UPPER}_INCLUDE_DIR ${${_NAME}_SOURCE_DIR} CACHE PATH "${_NAME} include directory" )
   SET( ${_NAME_UPPER}_LIBRARY_DIR ${${_NAME}_BINARY_DIR} CACHE PATH "${_NAME} library directory" )
   SET( ${_NAME_UPPER}_LIBRARY_FLAGS "-L${${_NAME}_BINARY_DIR} -l${LIBNAME}" CACHE STRING "{_NAME} linker flags")

   MESSAGE( STATUS "propagating local library ${_NAME}" )
   MESSAGE( STATUS "  include dir: ${_NAME_UPPER}_INCLUDE_DIR=${${_NAME_UPPER}_INCLUDE_DIR}" )
   MESSAGE( STATUS "  library dir: ${_NAME_UPPER}_LIBRARY_DIR=${${_NAME_UPPER}_LIBRARY_DIR}" )
   MESSAGE( STATUS "  library flag: ${_NAME_UPPER}_LIBRARY_FLAGS=${${_NAME_UPPER}_LIBRARY_FLAGS}" )

ENDFUNCTION( PROPAGATE_LIBRARY )

